image:
  repository: ghcr.io/sertyg-a11/skillswap-frontend
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1
service:
  port: 80

ingress:
  enabled: true
  host: skillswap.localtest.me
  path: /

env: {}
resources: {}
