apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillswap-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillswap-rabbitmq
  template:
    metadata:
      labels:
        app: skillswap-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.auth.username }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.auth.password }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "check_running"]
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "status"]
            initialDelaySeconds: 30
            periodSeconds: 15
