apiVersion: v1
kind: Service
metadata:
  name: skillswap-rabbitmq
spec:
  selector:
    app: skillswap-rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: 5672
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: 15672
  type: {{ .Values.service.type }}
