apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillswap-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: skillswap-frontend }
  template:
    metadata:
      labels: { app: skillswap-frontend }
    spec:
      securityContext:
        runAsUser: 101
        runAsNonRoot: true
        fsGroup: 101
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{ containerPort: 8080 }]
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          readinessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
