image:
  repository: ghcr.io/sertyg-a11/skillswap-api-gateway
  tag: "dev"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8081"
  USER_SERVICE_URL: "http://skillswap-user-service:8082"
  MESSAGE_SERVICE_URL: "http://skillswap-message-service:8083"

ingress:
  enabled: true
  className: traefik
  host: api.skillswap.localtest.me
  path: /
  pathType: Prefix

probes:
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 15
    periodSeconds: 5
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 10

metrics:
  enabled: true
