image:
  repository: ghcr.io/sertyg-a11/skillswap-user-service
  tag: "dev"

env:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8082"
  SPRING_FLYWAY_TABLE: "flyway_schema_history_user"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://skillswap-postgres:5432/skillswap"
  SPRING_DATASOURCE_USERNAME: "skillswap"
  SPRING_DATASOURCE_PASSWORD: "skillswap"
  SPRING_DATA_REDIS_HOST: "skillswap-redis-master"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_RABBITMQ_HOST: "skillswap-rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "skillswap"
  SPRING_RABBITMQ_PASSWORD: "skillswap"
  KEYCLOAK_ISSUER_URI: "http://localhost:8180/realms/skillswap-dev"
  KEYCLOAK_JWK_SET_URI: "http://skillswap-keycloak-http/realms/skillswap-dev/protocol/openid-connect/certs"
