image:
  repository: ghcr.io/sertyg-a11/skillswap-frontend
  tag: "dev"                   # CI will replace with the commit SHA
ingress:
  host: skillswap.localtest.me
env:
  BACKEND_ORIGIN: "http://skillswap-backend:8080"
imagePullSecrets: []
#  - name: ghcr-credentials