image:
  repository: ghcr.io/sertyg-a11/skillswap-backend
  tag: "e272a02"

env:
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://skillswap-postgres:5432/skillswap"
  SPRING_DATASOURCE_USERNAME: "skillswap"
  SPRING_DATASOURCE_PASSWORD: "skillswap"