image:
  tag: "dev"                   # CI will replace with the commit SHA
env:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://skillswap-postgres:5432/skillswap"
  SPRING_DATASOURCE_USERNAME: "skillswap"
  SPRING_DATASOURCE_PASSWORD: "skillswap"
