image:
  repository: ghcr.io/sertyg-a11/skillswap-message-service
  tag: "dev"

env:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8083"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://skillswap-postgres:5432/skillswap"
  SPRING_DATASOURCE_USERNAME: "skillswap"
  SPRING_DATASOURCE_PASSWORD: "skillswap"
  SPRING_DATA_REDIS_HOST: "skillswap-redis-master"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_RABBITMQ_HOST: "skillswap-rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  USER_SERVICE_URL: "http://skillswap-user-service:8082"
  KEYCLOAK_ISSUER_URI: "http://keycloak:8080/realms/skillswap-dev"
